This is makeindex, version 2.15 [TeX Live 2016/W32TeX] (kpathsea + Thai support).
Scanning style file ./thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (12 entries accepted, 0 rejected).
Sorting entries....done (49 comparisons).
Generating output file thesis.acr....done (27 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
